# ./docker-compose.yml
version: '3.3'

networks:
  grafana-net:
    external:
      name: grafana_network

  remindme-net:
    external: false

services:
  bot:
    build: .
    depends_on:
        - mongo
    container_name: reminderbot-discord
    volumes:
           - ./Bot:/code
           - ./legal:/code/legal
           - ./logs:/code/logs
           - /usr/share/zoneinfo:/usr/share/zoneinfo
  
    stdin_open: true
    tty: true

    environment:
      - MONGO_CONN
      - MONGO_PORT
      - MONGO_ROOT_USER
      - MONGO_ROOT_PASS
      - BOT_TOKEN
      - BOT_ROOT_PREFIX
      - ADMIN_GUILD
      - PROMETHEUS_PORT

    restart: always
    networks:
      - remindme-net

  mongo:
    image: mongo
    container_name: reminderbot-mongo
    restart: always
    volumes:
        - ./data/db:/data/db
    ports:
        - 27018:27017
    expose:
        - 27017
        - 9091
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}

    networks:
      - remindme-net


  prometheus:
    image: prom/prometheus
    container_name: reminderbot-prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=20y'
    ports:
      - 40002:9090
    expose:
      - 9090

    networks:
      - remindme-net
      - grafana-net
        

