# ./docker-compose.yml
version: '3.3'

networks:
  reminder-net:
    external: false
  gray-net:
    external:
      name: gray-net

services:
  bot:
    build: .
    depends_on:
        - mongo
    container_name: reminderbot-discord
    volumes:
           - ./Bot:/code
           - /usr/share/zoneinfo:/usr/share/zoneinfo
  
    stdin_open: true
    tty: true

    environment:
      - MONGO_DB_CONN=${MONGO_DB_CONN}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASS}

    restart: always
    networks:
      - reminder-net
      - gray-net

    
  mongo:
    image: mongo
    container_name: reminderbot-mongo
    restart: always
    volumes:
        - ./data/db:/data/db
    ports:
        - 27018:27017
    expose:
        - 27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    networks:
      - reminder-net
        
  mongo-express:
    image: mongo-express
    container_name: reminderbot-mongoexpress
    restart: always
    ports:
      - 40001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASS}
    networks:
      - reminder-net
        

